#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.


# Get whoami in AWS, who is the user running this shell script

# Oracle Cloud IDs (OCIDs) https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/identifiers.htm



CALLER_OCID=$OCI_USER_ID
USER_ID=$OCI_USER_ID
OCI_REALM=$(echo $CALLER_OCID| cut -d. -f3)
echo $OCI_USER_ID
ACCOUNT_NUM=$OCI_USER_ID
if [[ $ACCOUNT_TO_ASSUME ]]; then
  ACCOUNT_NUM=$ACCOUNT_TO_ASSUME
fi

getWhoami(){
  if [[ "$MODE" == "csv" ]]; then
    if [[ 255 -eq $? ]]; then
      # Failed to get own identity ... exit
      echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
      >&2 echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
      EXITCODE=2
      exit $EXITCODE
    fi
    printCsvHeader
    textTitle "0.0" "Show report generation info" "NOT_SCORED" "SUPPORT"
    textInfo "ARN: $CALLER_OCID  TIMESTAMP: $SCRIPT_START_TIME"
  elif [[ "$MODE" == "json" || "$MODE" == "json-asff" ]]; then
    :
  else
    echo ""
    echo -e " This report is being generated using credentials below:\n"
    echo -e " OCI-CLI Profile: $NOTICE[$PROFILE]$NORMAL OCI API Region: $NOTICE[$REGION]$NORMAL OCI Filter Region: $NOTICE[${FILTERREGION:-all}]$NORMAL"
    if [[ $MONOCHROME -eq 1 ]]; then
      echo -e " OCI Account: $NOTICE[$ACCOUNT_NUM]$NORMAL UserId: $NOTICE[$USER_ID]$NORMAL"
      echo -e " Caller Identity OCID: $NOTICE[$CALLER_OCID]$NORMAL"
      if [[ 255 -eq $? ]]; then
        # Failed to get own identity ... exit
        echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
        >&2 echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
        exit 2
      fi
    else
      echo -e " OCI Account: $NOTICE[$ACCOUNT_NUM]$NORMAL UserId: $NOTICE[$USER_ID]$NORMAL"
      echo -e " Caller Identity OCID: $NOTICE[$CALLER_OCID]$NORMAL"
      if [[ 255 -eq $? ]]; then
        # Failed to get own identity ... exit
        echo variable $PROFILE_OPT
        echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
        >&2 echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
        EXITCODE=2
        exit $EXITCODE
      fi
      echo ""
    fi
  fi
}
