#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

CHECK_ID_check113="1.13"
CHECK_TITLE_check113="[check113] Ensure MFA is enabled for the root account (Scored)"
CHECK_SCORED_check113="SCORED"
CHECK_TYPE_check113="LEVEL1"
CHECK_ASFF_TYPE_check113="Software and Configuration Checks/Industry and Regulatory Standards/CIS AWS Foundations Benchmark"
CHECK_ALTERNATE_check113="check113"

check113(){
  # "Ensure MFA is enabled for the root account (Scored)"
  MFA=$(cat $TEMP_REPORT_FILE |grep 'TAS_TENANT_ADMIN_USER' |awk -F',' '{ print $25 }')
  
  if [ "$COMMAND113" == "True" ]; then
    textPass "Virtual MFA is enabled for root"
  else
    textFail "MFA is not ENABLED for root account"
  fi
}
