#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Government of Canada Cloud Guardrails Exentions
# Eric Maia and Scott Levac Treasury Board of Canada Secretariat
# December 2019
# Group built specifically for al the checks needed to pass the GC Guardrails
GROUP_ID[1]='test2'
GROUP_NUMBER[1]='2.0'
GROUP_TITLE[1]='Check Test'
GROUP_RUN_BY_DEFAULT[1]='N' # run it when execute_all is called
#GROUP_CHECKS[1]='check11,check112,check113,extragc32,check110,check12'
#GROUP_CHECKS[1]=',extragc4,extragc62,extragc63,extragc41,extragc50,extra729,extragc71,extra713,check26'
GROUP_CHECKS[1]='check11'